# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: view performance

evaluateOptions:
  maxConcurrency: 10

prompts:
  - file://prompt.txt

providers:
  - id: file://instructor_provider.py:call_api_gpt
    config:
      model: gpt-4o
      label: GPT-4o
      temperature: 0
  - id: file://instructor_provider.py:call_api_gemini
    config:
      model: gemini/gemini-2.5-flash
      label: gemini/gemini-2.5-flash

tests:
  - vars:
      input:
        file://C://code//NL_2_DST//alphorn_text//alphorn-5-riskassessment-happy-path.txt
      expected_output:
        file://testinput//groundtruth_5.json
    assert: &grading_assert
      - type: python
        value: file://../scoring/grading.py:grading
  - vars:
      input:
        file://C://code//NL_2_DST//alphorn_text//alphorn-2-riskassessment.txt
      expected_output:
        file://testinput//groundtruth_5.json
    assert: *grading_assert

  - vars:
      input:
        file://C://code//NL_2_DST//alphorn_text//alphorn-3-riskassessment.txt
      expected_output:
        file://testinput//groundtruth_5.json
    assert: *grading_assert