@startuml
!include <domainstory/Domainstory>
!include <material/common>
!include <material/car>

!unquoted procedure Car($name, $label = "", $tag = "", $note = "", $shape = $Actor_Shape, $scale = $Actor_IconScale, $color = $Actor_IconColor, $background = "")
    Object("$id", "$ma_car", $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endprocedure

!include <material/view_list>

!unquoted procedure Catalog($name, $label = "", $tag = "", $note = "", $shape = $Actor_Shape, $scale = $Actor_IconScale, $color = $Actor_IconColor, $background = "")
    Object("$id", "$ma_view_list", $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endprocedure

!include <material/currency_eur>
!unquoted procedure Euro($name, $label = "", $tag = "", $note = "", $shape = $Actor_Shape, $scale = $Actor_IconScale, $color = $Actor_IconColor, $background = "")
    Object("$id", "$ma_currency_eur", $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endprocedure

!include <material/security>

!unquoted procedure Risk($name, $label = "", $tag = "", $note = "", $shape = $Actor_Shape, $scale = $Actor_IconScale, $color = $Actor_IconColor, $background = "")
    Object("$id", "$ma_security", $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endprocedure

!include ../icons/vote.puml
!include C:\code\NL_2_DST\icons\report.puml

Vote(vote, voting result)
Report(credit_rating, credit rating, $note="An evaluation of the credit risk of the customer. \nExpressed by a letter from A (excellent) to D (poor)")
Report(credit_rating2, credit rating)


Person(riskmanager, risk manager)
Person(rating_agency, rating agency)

Euro(monthly_installment, monthly installment)

Document(contract, $label=contract)
Document(contract2, $label=contract)


activity(1, riskmanager, fetches, credit_rating, for , contract )
activity(, contract, from, rating_agency)
activity(2, riskmanager, votes, contract2,with,vote)
activity(, vote, based on, monthly_installment)
activity(, vote, and, credit_rating2)


Person(salesperson, sales person)
Document(contract3, $label=voted contract)
Document(contract4, $label=voted contract)
activity(3, riskmanager, passes on, contract3, to, salesperson)
activity(4, salesperson, signs, contract4)


@enduml