@startuml
!include <domainstory/Domainstory>

!include <material/currency_eur>
!unquoted procedure Euro($name, $label = "", $tag = "", $note = "", $shape = $Actor_Shape, $scale = $Actor_IconScale, $color = $Actor_IconColor, $background = "")
    Object("$id", "$ma_currency_eur", $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endprocedure


sprite mdiAccountBox <svg width="48" height="48"><g transform="scale(2)"><path d="M6,17C6,15 10,13.9 12,13.9C14,13.9 18,15 18,17V18H6M15,9A3,3 0 0,1 12,12A3,3 0 0,1 9,9A3,3 0 0,1 12,6A3,3 0 0,1 15,9M3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3H5C3.89,3 3,3.9 3,5Z" /></g></svg>
!unquoted procedure BankAccount($name, $label = "", $tag = "", $note = "", $shape = $Actor_Shape, $scale = $Actor_IconScale, $color = $Actor_IconColor, $background = "")
  Object("$id", "$mdiAccountBox", $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endprocedure

sprite mdiBank <svg width="48" height="48"><g transform="scale(2)"><path d="M11.5,1L2,6V8H21V6M16,10V17H19V10M2,22H21V19H2M10,10V17H13V10M4,10V17H7V10H4Z" /></g></svg>
!unquoted procedure Bank($name, $label = "", $tag = "", $note = "", $shape = $Actor_Shape, $scale = $Actor_IconScale, $color = $Actor_IconColor, $background = "")
  Object("$id", "$mdiBank", $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endprocedure


sprite mdiAlertCircle <svg width="48" height="48"><g transform="scale(2)"><path d="M13,13H11V7H13M13,17H11V15H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"  /></g></svg>
!unquoted procedure Alert($name, $label="", $tag="", $note="", $shape=$Object_Shape, $scale=$Object_IconScale, $color=$Object_IconColor, $background="")
  Object("$id", "$mdiAlertCircle", $name, $label)
!endprocedure

Person(customer, customer, $color="DarkGreen", $scale=1.5, $note="has not paid monthly installment")
Person(accountant, accountant, $color="DarkGreen", $scale=1.5)
Person(risk_manager, risk_manager, $color="DarkGreen", $scale=1.5)

Document(dunning_letter, dunning letter)
Euro(monthly_installment, monthly installment,  $note="does not find it")

BankAccount(bank_account, bank account)
Bank(bank, bank)


Alert(unpaid_installment, unpaid installment, $note=""                                                                  )

activity(1,customer, searches, monthly_installment, in, bank_account)
activity(, bank_account, at, bank)
activity(2, accountant, informs about, unpaid_installment, the, risk_manager)
activity(3, accountant, sends, dunning_letter, to, customer)

@enduml