@startuml
!include <domainstory/Domainstory>
title <size:24><b>Car leasing process</b></size>
Person(customer,customer,$color="DarkGreen", $scale=1.5)
Person(salesperson,salesperson,$color="DarkGreen", $scale=1.5)
Person(risk_manager,risk manager,$color="DarkGreen", $scale=1.5)

                sprite mdiCarSelect <svg width="48" height="48"><g transform="scale(2)"><path d="M5 13L6.5 8.5H17.5L19 13M17.5 18C16.7 18 16 17.3 16 16.5S16.7 15 17.5 15 19 15.7 19 16.5 18.3 18 17.5 18M6.5 18C5.7 18 5 17.3 5 16.5S5.7 15 6.5 15 8 15.7 8 16.5 7.3 18 6.5 18M18.9 8C18.7 7.4 18.1 7 17.5 7H6.5C5.8 7 5.3 7.4 5.1 8L3 14V22C3 22.6 3.4 23 4 23H5C5.6 23 6 22.6 6 22V21H18V22C18 22.6 18.4 23 19 23H20C20.6 23 21 22.6 21 22V14M8 1L12 5.5L16 1Z" /></g></svg>

                !unquoted procedure car($name, $label = "", $tag = "", $note = "", $shape = $Object_Shape, $scale = $Object_IconScale, $color = $Object_IconColor, $background = "")

                  Object($name, "$mdiCarSelect", $name, $label, $tag, $note, $shape, $scale, $color, $background)

                !endprocedure


                sprite mdiOffer <svg width="48" height="48"><g transform="scale(2)"><path d="M21 13C21.6 13 22.1 13.2 22.4 13.6C22.8 14 23 14.5 23 15L15 18L8 16V7H9.9L17.2 9.7C17.7 9.9 18 10.3 18 10.8C18 11.1 17.9 11.4 17.7 11.6C17.5 11.8 17.2 12 16.8 12H14L12.3 11.3L12 12.2L14 13H21M2 7H6V18H2V7Z" /></g></svg>

                !unquoted procedure offer($name, $label = "", $tag = "", $note = "", $shape = $Object_Shape, $scale = $Object_IconScale, $color = $Object_IconColor, $background = "")

                  Object($name, "$mdiOffer", $name, $label, $tag, $note, $shape, $scale, $color, $background)

                !endprocedure


                sprite mdiFileSign <svg width="48" height="48"><g transform="scale(2)"><path d="M19.7 12.9L14 18.6H11.7V16.3L17.4 10.6L19.7 12.9M23.1 12.1C23.1 12.4 22.8 12.7 22.5 13L20 15.5L19.1 14.6L21.7 12L21.1 11.4L20.4 12.1L18.1 9.8L20.3 7.7C20.5 7.5 20.9 7.5 21.2 7.7L22.6 9.1C22.8 9.3 22.8 9.7 22.6 10C22.4 10.2 22.2 10.4 22.2 10.6C22.2 10.8 22.4 11 22.6 11.2C22.9 11.5 23.2 11.8 23.1 12.1M3 20V4H10V9H15V10.5L17 8.5V8L11 2H3C1.9 2 1 2.9 1 4V20C1 21.1 1.9 22 3 22H15C16.1 22 17 21.1 17 20H3M11 17.1C10.8 17.1 10.6 17.2 10.5 17.2L10 15H8.5L6.4 16.7L7 14H5.5L4.5 19H6L8.9 16.4L9.5 18.7H10.5L11 18.6V17.1Z" /></g></svg>

                !unquoted procedure contract($name, $label = "", $tag = "", $note = "", $shape = $Object_Shape, $scale = $Object_IconScale, $color = $Object_IconColor, $background = "")

                  Object($name, "$mdiFileSign", $name, $label, $tag, $note, $shape, $scale, $color, $background)

                !endprocedure


                sprite mdiLockPercent <svg width="48" height="48"><g transform="scale(2)"><path d="M18 8H17V6C17 3.2 14.8 1 12 1S7 3.2 7 6V8H6C4.9 8 4 8.9 4 10V20C4 21.1 4.9 22 6 22H18C19.1 22 20 21.1 20 20V10C20 8.9 19.1 8 18 8M9 6C9 4.3 10.3 3 12 3S15 4.3 15 6V8H9V6M9.5 11C10.3 11 11 11.7 11 12.5S10.3 14 9.5 14 8 13.3 8 12.5 8.7 11 9.5 11M14.5 19C13.7 19 13 18.3 13 17.5S13.7 16 14.5 16 16 16.7 16 17.5 15.3 19 14.5 19M9.2 19.2L7.8 17.8L14.9 10.7L16.3 12.1L9.2 19.2Z" /></g></svg>

                !unquoted procedure risk($name, $label = "", $tag = "", $note = "", $shape = $Object_Shape, $scale = $Object_IconScale, $color = $Object_IconColor, $background = "")

                  Object($name, "$mdiLockPercent", $name, $label, $tag, $note, $shape, $scale, $color, $background)

                !endprocedure


                sprite mdiBallotRecount <svg width="48" height="48"><g transform="scale(2)"><path d="M19,12V13.5A4,4 0 0,1 23,17.5C23,18.32 22.75,19.08 22.33,19.71L21.24,18.62C21.41,18.28 21.5,17.9 21.5,17.5A2.5,2.5 0 0,0 19,15V16.5L16.75,14.25L19,12M19,23V21.5A4,4 0 0,1 15,17.5C15,16.68 15.25,15.92 15.67,15.29L16.76,16.38C16.59,16.72 16.5,17.1 16.5,17.5A2.5,2.5 0 0,0 19,20V18.5L21.25,20.75L19,23M10,17H7V14H10V17M10,7V10H7V7H10M5,21A2,2 0 0,1 3,19V5A2,2 0 0,1 5,3H19A2,2 0 0,1 21,5V11.17C20.5,11.06 20,11 19.5,11A6.5,6.5 0 0,0 13,17.5C13,18.79 13.38,20 14,21H5M13,9.5H18V7.5H13V9.5M11,13H6V18H11V13M11,6H6V11H11V6Z" /></g></svg>

                !unquoted procedure voting_result($name, $label = "", $tag = "", $note = "", $shape = $Object_Shape, $scale = $Object_IconScale, $color = $Object_IconColor, $background = "")

                  Object($name, "$mdiBallotRecount", $name, $label, $tag, $note, $shape, $scale, $color, $background)

                !endprocedure


                sprite mdiCashSync <svg width="48" height="48"><g transform="scale(2)"><path d="M3 6V18H13.32C13.1 17.33 13 16.66 13 16H7C7 14.9 6.11 14 5 14V10C6.11 10 7 9.11 7 8H17C17 9.11 17.9 10 19 10V10.06C19.67 10.06 20.34 10.18 21 10.4V6H3M12 9C10.3 9.03 9 10.3 9 12S10.3 14.94 12 15C12.38 15 12.77 14.92 13.14 14.77C13.41 13.67 13.86 12.63 14.97 11.61C14.85 10.28 13.59 8.97 12 9M19 11L21.25 13.25L19 15.5V14C17.15 14 15.94 15.96 16.76 17.62L15.67 18.71C13.91 16.05 15.81 12.5 19 12.5V11M19 22L16.75 19.75L19 17.5V19C20.85 19 22.06 17.04 21.24 15.38L22.33 14.29C24.09 16.95 22.19 20.5 19 20.5V22" /></g></svg>

                !unquoted procedure monthly_installment($name, $label = "", $tag = "", $note = "", $shape = $Object_Shape, $scale = $Object_IconScale, $color = $Object_IconColor, $background = "")

                  Object($name, "$mdiCashSync", $name, $label, $tag, $note, $shape, $scale, $color, $background)

                !endprocedure

car(car_1, car)
car(car_2, car)
car(car_3, car)
car(car_4, car)
offer(offer_1, offer)
contract(contract_1, contract)
contract(contract_2, contract)
contract(contract_3, contract)
contract(contract_4, contract)
contract(contract_5, contract)
risk(risk_1, risk)
voting_result(voting_result_1, voting result)
monthly_installment(monthly_installment_1, monthly installment)
activity(1, customer, chooses, car_1, , )
activity(2, customer, asks for, offer_1, from, salesperson)
activity(3, salesperson, offers, contract_1, to, customer)
activity( , contract_1, for, car_2)
activity( , contract_1, with, monthly_installment_1)
activity(4, customer, signs, contract_2, with, salesperson)
activity(5, salesperson, passes on, contract_3, to, risk_manager)
activity(6, risk_manager, assesses, risk_1, for, contract_4)
activity(7, risk_manager, votes on, contract_5, , )
activity(8, risk_manager, informs, voting_result_1, to, salesperson)
activity(9, salesperson, hands over, car_3, to, customer)
activity(10, customer, pays, monthly_installment_1, , )
activity(11, customer, returns, car_4, to, salesperson)
@enduml